# Generated by Django 3.2.7 on 2021-09-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0006_auto_20210907_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
