# Generated by Django 3.2.7 on 2021-09-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0007_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/avatars'),
        ),
    ]
