# Generated by Django 3.2.7 on 2021-09-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0011_alter_blog_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
