# Generated by Django 3.2.7 on 2021-09-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0018_alter_blog_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
