# Generated by Django 3.2.7 on 2021-09-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0024_alter_contacts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
