# Generated by Django 3.1.1 on 2021-10-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0026_auto_20210923_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_post',
            options={'ordering': ['is_approved']},
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
